### ISSUE TITLE
Profile Comp

### ISSUE THREAD

**Issue by jwright** [brilliantfantastic/tatsu-issues#21]
- [x] Ability to change channel on profile
- [x] Link to instructions
- [x] Link to commands
- [x] Cancel account
- [x] Pat yourself on the back!

**Comment by jonmspencer** [comment]
@cestridge also please add a "cancel your plan" option on the profile page.

**Comment by cestridge** [comment]
https://www.dropbox.com/s/tnhtvebaz1yoqy2/Tatsu%20Account%20Settings.psd?dl=0
