### ISSUE TITLE
Activity Page Comp

### ISSUE THREAD

**Issue by jwright** [brilliantfantastic/tatsu-issues#24]

**Comment by cestridge** [comment]
https://www.dropbox.com/s/sbgpzxn9wnoheuw/Tatsu%20Activity.psd?dl=0
or
https://www.dropbox.com/s/9dqt8dkqf5p25zp/Tatsu%20Activity%202.psd?dl=0

**Comment by cestridge** [comment]
Didnt get too fancy with the different states. Added a back and forward button at the bottom.

**Comment by cestridge** [comment]
Forgot the numbers

**Comment by cestridge** [comment]
Updated the comp. I gave 2 options. 1 is Scott's answer, its more straight forward. 2 is Josh's answer, I tweaked it and added numbers in circles.
