### ISSUE TITLE
Edit Your Answers

### ISSUE THREAD

**Issue by jwright** [brilliantfantastic/tatsu-issues#5]
As a participant
I should be able to edit my answers to the questions
So that I can easily update my standup

**Comment by jwright** [comment]
Should be something like

```
participant> edit #2
```

or

```
participant> edit
bot> What question would you like to edit (1, 2, or 3)?
participant> 3
```

**Comment by jwright** [comment]
Should also handle:

```
participant> edit
bot> You have not gone yet @participant. Hold tight or say "ready"
```

**Comment by kylegolem** [comment]
Very cool :+1: carry on with your fantastical lifestyle.

**Comment by jwright** [comment]
Closing because it was moved to the project page
